### ISSUE TITLE
记录和总结

### ISSUE THREAD

**Issue by 100209** [100209/Blue-Ocean-Strategy#15]
# JavaScript

### 方法一：使用正则表达式获取某个参数
```javascript
const getParam = name => {
  const reg = new RegExp(`(^|&)${name}=([^&]*)(&|$)`)
  const res = window.location.search.substr(1).match(reg)
  if (res !== null) {
    return decodeURIComponent(res[2])
  }
  return null
}
```
### 方法二：获取所有的参数
```javascript
const getParams = () => {
  const queryString = window.location.search
  const params = {}
  if (queryString.indexOf('?') !== -1) {
    let str = queryString.substr(1)
    let strArr = str.split('&')
    for (let i = 0; i < strArr.length; i++) {
      params[strArr[i].split('=')[0]] = decodeURIComponent(strArr[i].split('=')[1])
    }
  }
  return params
}
```

**Comment by 100209** [comment]
# CSS

## 背景属性
```css
.bg {
  /* 背景颜色，背景图加载过程中会显示背景色 */
  background-color: #eee;
  background-image: url();
  background-repeat: no-repeat;

  /* 背景图全屏 */
  background-size: 100% 100%;

  /* 背景图垂直、水平居中 */
  background-position: center center;

  /* 背景图基于容器大小伸缩，背景图按比例缩放直至背景图宽高不小于容器的宽高 */
  background-size: cover;
}
```
