### ISSUE TITLE
记录和总结

### ISSUE THREAD

**Issue by 100209** [100209/Blue-Ocean-Strategy#16]
## 背景属性
```css
.bg {
  /* 背景颜色，背景图加载过程中会显示背景色 */
  background-color: #eee;
  background-image: url();
  background-repeat: no-repeat;

  /* 背景图全屏 */
  background-size: 100% 100%;

  /* 背景图垂直、水平居中 */
  background-position: center center;

  /* 背景图基于容器大小伸缩，背景图按比例缩放直至背景图宽高不小于容器的宽高 */
  background-size: cover;
}
```
